import type { Metadata } from "next";
import { PlayfairDisplay, PlayfairDisplayItalic, sans } from "@/lib/font";
import "./globals.css";
import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${PlayfairDisplay.variable} ${PlayfairDisplayItalic.variable} ${sans.variable} antialiased`}
      lang="en"
    >
      <body className="font-sans">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
