import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display, Open_Sans } from "next/font/google";
import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";

const Playfair = Playfair_Display({
  variable: "--font-PlayfairDisplay",
  subsets: ["latin"],
});

const OpenSans = Open_Sans({
  variable: "--font-OpenSans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={`${Playfair.variable} ${OpenSans.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
